#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation, and any use by you of this program is subject to the terms of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained from Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

ifeq ($(CONFIG_MALI_TMIX),y)
	ifeq ($(CONFIG_MALI_TMIX_R5P0),y)
		obj-y += tMIx/r5p0/
	endif
endif
ifeq ($(CONFIG_MALI_THEX),y)
	ifeq ($(CONFIG_MALI_THEX_R5P0),y)
		obj-y += tHEx/r5p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R7P0),y)
		obj-y += tHEx/r7p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R8P0),y)
		obj-y += tHEx/r8p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R9P0),y)
		obj-y += tHEx/r9p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R10P0),y)
		obj-y += tHEx/r10p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R12P0),y)
		obj-y += tHEx/r12p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R15P0),y)
		obj-y += tHEx/b_r15p0/
	endif
	ifeq ($(CONFIG_MALI_THEX_R16P0),y)
		obj-y += tHEx/b_r16p0/
	endif
	ifeq ($(CONFIG_MALI_BIFROST_R19P0_Q),y)
		obj-y += b_r19p0/
	endif
endif

# ---------------------------------------------------------------------------
# Always be able to produce a built-in.o for this directory.
#
# drivers/gpu/Makefile descends here unconditionally ("obj-y += arm/") and
# scripts/Makefile.lib turns every "obj-y" entry ending in "/" into a hard
# "<dir>/built-in.o" prerequisite of the parent link, regardless of whether
# this directory has any objects of its own.  When no generation above is
# selected - which is the case for any SoC that drivers/gpu/arm/Kconfig does
# not gate on, e.g. Exynos 7885 - this directory would contribute nothing,
# scripts/Makefile.build would never define builtin-target for it, and
# drivers/gpu/built-in.o would fail to link with
#
#   ld.bfd: cannot find drivers/gpu/arm/built-in.o: No such file or directory
#
# Add one placeholder object in exactly that case so the aggregate always
# exists.  Correctly configured builds (any MALI_TMIX/MALI_THEX generation
# selected) are unaffected and never compile the stub.
# ---------------------------------------------------------------------------
ifeq ($(strip $(obj-y) $(obj-m)),)
obj-y += mali_arm_ddk_stub.o
endif
